# Load others files
# bash/env     : Environment variables for other aplications
# bash/config  : Prompt and Shell settings 
# bash/aliases :

source ~/bin/dotfiles/bash/env
source ~/bin/dotfiles/bash/config
source ~/bin/dotfiles/bash/aliases
